### ISSUE TITLE
Build containers also for Raspberry Pi

### ISSUE THREAD

**Issue by bboelaert** [Icinga/docker-icinga2#27]
Hi,

Whenever I run a command for starting up an Icinga2 Docker container, I receive the following error message :+1: standard_init_linux.go:211: exec user process caused "exec format error"
e.g.
docker run --rm -h icinga-host -v /data/icinga2:/data -e ICINGA_MASTER=1 icinga/icinga2 icinga2 daemon -C

I'm using the latest image version.
Please fix ASAP!

Kind regards,

Bart.

**Comment by Al2Klimov** [comment]
Hello @bboelaert and thank you for reporting!

Please share the output of `uname -a`.

Best,
AK

**Comment by bboelaert** [comment]
Hi,

I want to run it on a RPi 3/4. Below is the output of uname -a :

Linux jolimon2 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux

Kind regards,

Bart.

**Comment by Al2Klimov** [comment]
@N-o-X Shall we do this?

**Comment by mzac** [comment]
This would be a great addition to have ARM builds as well.  I'm running a k3s arm64 cluster at home with multiple PIs and would love to migrate my Icinga install into a container rather than a monolithic install.

https://github.com/docker/setup-buildx-action

**Comment by fabriciomrtnz** [comment]
Hello,

I too would love to have this working in arm64.

Thank you.
