### ISSUE TITLE
Replace lsb_release with os-release

### ISSUE THREAD

**Issue by widhalmt** [Icinga/docker-icinga2#3]
We shouldn't rely on `lsb_release` to determine which base image we are using. It's better to read `/etc/os-release`.

Thanks @lazyfrosch  for the hint.

**Comment by Al2Klimov** [comment]
Hello @widhalmt!

Any news from your side? (You're assigned after all.)

Best,
AK

**Comment by julianbrost** [comment]
There's no reference to lsb_release in this repo (anymore, 7c36ba66438ffc251e3b3973718db4383604f1cd removed things using lsb_release). So I think no action is needed here.
