### ISSUE TITLE
Add possibility to send mail notifications from the container

### ISSUE THREAD

**Issue by mcktr** [Icinga/docker-icinga2#41]
Hi,

I am currently evaluating a Icinga 2 docker setup. During my evaluation I came across the topic _mail notification_, currently I see no possibility to send such from a container based on this image. Is it possible to add this feature?

I found a icinga2 docker image which has this possibility, the image integrated `msmtp` to send mails:

https://github.com/jjethwa/icinga2#sending-notification-mails

Thanks and best regards
Michael

**Comment by dwt** [comment]
Just stumbled on this problem too - would very much appreciate if that ssmtp pull request gets merged.
