### ISSUE TITLE
Check for database schema and eventually create it

### ISSUE THREAD

**Issue by widhalmt** [Icinga/docker-icinga2#5]
We need a way of connecting to the database, check for the current schema and decide:

* If there's no schema at all, import the schema file
* If there's a schema but not the current one, apply all required update scripts in the correct order

So a prerequisite of the container would be to have a user who is allowed to run all `.sql` scripts relevant for the schema.

**Comment by Al2Klimov** [comment]
I opt for not creating **the IDO schema** as (1) having to import the schema manually once isn't something new and (2) we'd like new users to prefer Icinga DB.

So we don't make it harder for IDO users, but easier for Icinga DB users (Icinga/docker-icingadb#4).

**Comment by Al2Klimov** [comment]
@widhalmt Could you (and the customers) live with that?

**Comment by widhalmt** [comment]
From my side we can live with that. I created this ticket as part of the design decisions we had in the first meetings.
