### ISSUE TITLE
Rootless icinga/icinga2: mail is not working

### ISSUE THREAD

**Issue by christian-2** [Icinga/docker-icinga2#74]
I'm trying to bring up `icinga/icinga2` and `icinga/icingaweb2` with Podman; looks good so far. Could you please comment on whether these images could possibly run as rootless containers? Inspection of the Dockerfile (with `USER icinga` and `USER www-data` respectively) suggests that this could be the case; on the other hand I currently observe that mail is app. not working  in a rootless instance of `icinga/icinga2` (but it is working on a non-rootless instance that was started with `Docker`). What is your general recommendation on rootless operation of these images?

**Comment by Al2Klimov** [comment]
Hi,

We've designed them for rootless instances.

**Comment by christian-2** [comment]
Thanks for your quick response. In this case the remaining error is perhaps in my MTA setup and I'll focus there.
