### ISSUE TITLE
Password for Webinterface

### ISSUE THREAD

**Issue by Its-egner** [Icinga/docker-icinga2#75]
There is a Basic authentication for the Webinterface, what are the Credentials? I couldnt find it anywhere.

**Comment by julianbrost** [comment]
If by basic auth, you mean HTTP basic auth (i.e. browser renders a login window), that shouldn't be coming from our Docker images. If you mean the Icinga Web 2 login page, the credentials depend on the environment variables you use to start that container, see the [README](https://github.com/Icinga/docker-icingaweb2/blob/master/README.md):

```
	-e icingaweb.passwords.icingaweb2.icingaadmin=123456 \
```

That would create the user `icingaadmin` with password `123456`.
