### ISSUE TITLE
Missing package - bind9-dnsutils for nslookup

### ISSUE THREAD

**Issue by mzac** [Icinga/docker-icinga2#88]
I am trying to use the **check_dns** plugin however it won't work since nslookup is missing.  This should be part of the **bind9-dnsutils** package.  Can this package be added to the image?

```
DNS CRITICAL - '/usr/bin/nslookup -sil' msg parsing exited with no address
```

**Comment by Al2Klimov** [comment]
Meanwhile icinga/icinga2:master has nslookup.
